### ISSUE TITLE
.bin to big

### ISSUE THREAD

**Issue by lalo-uy** [rumpeltux/hc12#1]
Thanks for tool.
I try the firmwaredump.py but got many error and zero size fw.bin
Any way the +VER got patched and sending the command dump the firmware.
Size was 32787. Then I realize that the first 19 bytes where the original version string.
Any way 32k was to big.
Code after address 0x1FFF  is all 0x90.
Version is 2.3
Is this correct?

**Comment by rumpeltux** [comment]
Clearly not. Maybe you have a different firmware version for which the dump tool doesn’t work.
